import { AevoInstrument } from "../types";

export const getInstrumentById = (id: string | number): AevoInstrument | null =>
  AEVO_INSTRUMENTS.find((i) => i.instrument_id === id.toString()) || null;

export const getInstrumentByName = (name: string): AevoInstrument | null =>
  AEVO_INSTRUMENTS.find((i) => i.underlying_asset === name.toString()) || null;

export const AEVO_INSTRUMENTS: AevoInstrument[] = [
  {
    instrument_id: "8797",
    instrument_name: "CANTO-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "CANTO",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.300502",
    index_price: "0.301151",
    is_active: true,
    max_leverage: "5",
  },
  {
    instrument_id: "4042",
    instrument_name: "BNB-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BNB",
    quote_asset: "USDC",
    price_step: "0.05",
    amount_step: "0.01",
    min_order_value: "10",
    mark_price: "243.099765",
    index_price: "243.475446",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "9605",
    instrument_name: "STRAX-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "STRAX",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "1.232585",
    index_price: "1.232897",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "8139",
    instrument_name: "HIFI-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "HIFI",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.7287",
    index_price: "0.728699",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "12522",
    instrument_name: "BEAMX-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BEAMX",
    quote_asset: "USDC",
    price_step: "0.000001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.019748",
    index_price: "0.019724",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "5125",
    instrument_name: "MATIC-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "MATIC",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.837499",
    index_price: "0.837819",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "9924",
    instrument_name: "TRB-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "TRB",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "109.973778",
    index_price: "110.003202",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "8341",
    instrument_name: "MKR-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "MKR",
    quote_asset: "USDC",
    price_step: "0.1",
    amount_step: "0.001",
    min_order_value: "10",
    mark_price: "1339.349962",
    index_price: "1338.144788",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "11312",
    instrument_name: "1000BONK-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "1000BONK",
    quote_asset: "USDC",
    price_step: "0.000001",
    amount_step: "100",
    min_order_value: "10",
    mark_price: "0.023988",
    index_price: "0.023947",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "7349",
    instrument_name: "ARB-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "ARB",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "1.133954",
    index_price: "1.133988",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "13987",
    instrument_name: "ATOM-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "ATOM",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "0.01",
    min_order_value: "10",
    mark_price: "11.349218",
    index_price: "11.365515",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "12418",
    instrument_name: "BLAST-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BLAST",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "7.373252",
    index_price: "0",
    is_active: true,
    pre_launch: true,
    max_leverage: "2",
  },
  {
    instrument_id: "3396",
    instrument_name: "BTC-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BTC",
    quote_asset: "USDC",
    price_step: "0.1",
    amount_step: "0.001",
    min_order_value: "10",
    mark_price: "42063.997808",
    index_price: "42094.446579",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "8833",
    instrument_name: "BITCOIN-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BITCOIN",
    quote_asset: "USDC",
    price_step: "0.00001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.082608",
    index_price: "0.081523",
    is_active: true,
    max_leverage: "5",
  },
  {
    instrument_id: "11969",
    instrument_name: "DOGE-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "DOGE",
    quote_asset: "USDC",
    price_step: "0.00001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.094998",
    index_price: "0.095043",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "1",
    instrument_name: "ETH-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "ETH",
    quote_asset: "USDC",
    price_step: "0.01",
    amount_step: "0.01",
    min_order_value: "10",
    mark_price: "2244.212658",
    index_price: "2244.502924",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "9451",
    instrument_name: "T-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "T",
    quote_asset: "USDC",
    price_step: "0.00001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.02467",
    index_price: "0.024678",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "5514",
    instrument_name: "WLD-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "WLD",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "1",
    mark_price: "4.646359",
    index_price: "4.64464",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "8543",
    instrument_name: "OX-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "OX",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.013336",
    index_price: "0.013292",
    is_active: true,
    max_leverage: "5",
  },
  {
    instrument_id: "13882",
    instrument_name: "10000SATS-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "10000SATS",
    quote_asset: "USDC",
    price_step: "0.00001",
    amount_step: "100",
    min_order_value: "10",
    mark_price: "0.0073",
    index_price: "0.007296",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "11642",
    instrument_name: "APT-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "APT",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "8.326545",
    index_price: "8.328974",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "9060",
    instrument_name: "AVAX-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "AVAX",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "41.748924",
    index_price: "41.776463",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "12478",
    instrument_name: "BEAM-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BEAM",
    quote_asset: "USDC",
    price_step: "0.000001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.000001",
    index_price: "0.009163",
    is_active: false,
    pre_launch: true,
    max_leverage: "20",
  },
  {
    instrument_id: "10008",
    instrument_name: "BLUR-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BLUR",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.466327",
    index_price: "0.466351",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "13194",
    instrument_name: "ORDI-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "ORDI",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "50.992316",
    index_price: "50.988373",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "8583",
    instrument_name: "BLZ-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BLZ",
    quote_asset: "USDC",
    price_step: "0.00001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.347358",
    index_price: "0.34724",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "13091",
    instrument_name: "RNDR-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "RNDR",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "4.334166",
    index_price: "4.335178",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "5757",
    instrument_name: "CRV-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "CRV",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "1",
    min_order_value: "0.001",
    mark_price: "0.666569",
    index_price: "0.667299",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "8802",
    instrument_name: "HPOS-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "HPOS",
    quote_asset: "USDC",
    price_step: "0.00001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.090628",
    index_price: "0.090602",
    is_active: false,
    max_leverage: "5",
  },
  {
    instrument_id: "12938",
    instrument_name: "JUP-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "JUP",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.643173",
    index_price: "0",
    is_active: true,
    pre_launch: true,
    max_leverage: "2",
  },
  {
    instrument_id: "11460",
    instrument_name: "LDO-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "LDO",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "2.138266",
    index_price: "2.138262",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "6104",
    instrument_name: "SEI-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "SEI",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.241581",
    index_price: "0.241435",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "8552",
    instrument_name: "GLMR-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "GLMR",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.32165",
    index_price: "0.321674",
    is_active: true,
    max_leverage: "10",
  },
  {
    instrument_id: "10504",
    instrument_name: "MEME-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "MEME",
    quote_asset: "USDC",
    price_step: "0.00001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.032276",
    index_price: "0.032269",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "5197",
    instrument_name: "SOL-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "SOL",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "73.99046",
    index_price: "74.072409",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "7530",
    instrument_name: "SYN-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "SYN",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "0.417913",
    index_price: "0.41798",
    is_active: true,
    max_leverage: "10",
  },
  {
    instrument_id: "8588",
    instrument_name: "TIA-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "TIA",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "13.137356",
    index_price: "13.138631",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "10009",
    instrument_name: "INJ-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "INJ",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "29.928745",
    index_price: "29.941339",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "9358",
    instrument_name: "DYDX-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "DYDX",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "3.250458",
    index_price: "3.250713",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "11849",
    instrument_name: "NTRN-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "NTRN",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "1.17693",
    index_price: "1.176909",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "12123",
    instrument_name: "TRX-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "TRX",
    quote_asset: "USDC",
    price_step: "0.00001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.102889",
    index_price: "0.103018",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "12479",
    instrument_name: "ILV-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "ILV",
    quote_asset: "USDC",
    price_step: "0.01",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "91.661799",
    index_price: "91.584497",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "8494",
    instrument_name: "LINK-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "LINK",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "0.01",
    min_order_value: "10",
    mark_price: "14.323092",
    index_price: "14.319662",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "10280",
    instrument_name: "MINA-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "MINA",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.765404",
    index_price: "0.76542",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "7348",
    instrument_name: "OP-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "OP",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "2.119036",
    index_price: "2.119268",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "11768",
    instrument_name: "PYTH-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "PYTH",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.386589",
    index_price: "0.38534",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "7020",
    instrument_name: "1000PEPE-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "1000PEPE",
    quote_asset: "USDC",
    price_step: "0.000001",
    amount_step: "100",
    min_order_value: "10",
    mark_price: "0.001383",
    index_price: "0.001384",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "13193",
    instrument_name: "JITO-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "JITO",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "2.799471",
    index_price: "2.795714",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "9764",
    instrument_name: "PRIME-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "PRIME",
    quote_asset: "USDC",
    price_step: "0.001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "9.230937",
    index_price: "9.015447",
    is_active: true,
    max_leverage: "5",
  },
  {
    instrument_id: "5196",
    instrument_name: "XRP-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "XRP",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "0.618355",
    index_price: "0.618505",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "7623",
    instrument_name: "BANANA-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "BANANA",
    quote_asset: "USDC",
    price_step: "0.0001",
    amount_step: "1",
    min_order_value: "10",
    mark_price: "12.700294",
    index_price: "12.656761",
    is_active: true,
    max_leverage: "2",
  },
  {
    instrument_id: "6815",
    instrument_name: "FRIEND-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "FRIEND",
    quote_asset: "USDC",
    price_step: "0.01",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "38.550428",
    index_price: "38.393604",
    is_active: true,
    max_leverage: "2",
  },
  {
    instrument_id: "7480",
    instrument_name: "NMR-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "NMR",
    quote_asset: "USDC",
    price_step: "0.01",
    amount_step: "0.1",
    min_order_value: "10",
    mark_price: "16.895307",
    index_price: "16.892259",
    is_active: true,
    max_leverage: "20",
  },
  {
    instrument_id: "11070",
    instrument_name: "TAO-PERP",
    instrument_type: "PERPETUAL",
    underlying_asset: "TAO",
    quote_asset: "USDC",
    price_step: "0.01",
    amount_step: "0.01",
    min_order_value: "10",
    mark_price: "318.049098",
    index_price: "313.960976",
    is_active: true,
    max_leverage: "5",
  },
];
